version: 1.0.{build}
os: Visual Studio 2015
clone_folder: C:\projects\fftw-cmake
test: off
configuration:
    - Release
    #- Debug
branches:
  only:
    - master
environment:
  matrix:
    - CMAKE_PLATFORM: "Visual Studio 14 2015"
    - CMAKE_PLATFORM: "Visual Studio 14 2015 Win64"
install:
  - cinstall: python
build_script:
  - echo Running cmake...
  - cd c:\projects
  - appveyor DownloadFile http://fftw.org/fftw-3.3.6-pl2.tar.gz
  - 7z x fftw-3.3.6-pl2.tar.gz
  - 7z x fftw-3.3.6-pl2.tar
  - xcopy C:\projects\fftw-cmake\* C:\projects\fftw-3.3.6-pl2 /s /e /y || exit 1
  - cd c:\projects\fftw-3.3.6-pl2
  - cmake -G "%CMAKE_PLATFORM%" -DBUILD_SHARED_LIBS=ON -DENABLE_THREADS=ON -DWITH_COMBINED_THREADS=ON .
  - cmake --build . --config %Configuration% --target tests
  - ctest -C Release
